http:
  addr: localhost:3456

mysql:
  user: leon
  password: "${LEON_MYSQL_PASSWORD}"
  host: localhost
  port: 3306
  dbname: "university_management"
  max_conn: 100
  max_idle_conn: 20
  max_conn_lifetime: 3600
  max_idle_time: 600

redis:
  ip: 127.0.0.1
  port: 6379
  pool_size: 100
  max_conn: 100
  conn_timeout: 1000
  read_timeout: 1000
  write_timeout: 100